### ISSUE TITLE
Exposed .env file

### ISSUE THREAD

**Issue by 0plaze0** [TrailblaZer132/ecommerce#1]
- .env file is pushed in the repo, which can lead to security threats.
- also node_modules was pushed to repo

use .gitignore to ignore .env and node_modules

if it's a example for developer to how to setup .env then use extension .example.env

**Comment by 0plaze0** [comment]
.ignore will not work right now since git is already watching the .env.

refer to this post for more info [link](https://stackoverflow.com/a/70001970/21180255)

or [link](https://www.s-soumyakanta.com/blog/how-to-remove-accidentally-pushed-env-file-in-git-history)

**Comment by TrailblaZer132** [comment]
Thanks for pointing that out. The issue has been fixed. I appreciate your efforts. Cheers!

**Comment by 0plaze0** [comment]
#1 you can close the issue

Cheers! If you have any cool project ideas, lets me know, I would like to contribute to that.

**Comment by TrailblaZer132** [comment]
Sure, Thanks again.
